import test from 'node:test';
import assert from 'node:assert/strict';
import {parseCSV,deduplicate,qualify,dateValue,exportCSV,SAMPLE_CSV,SAMPLE_DATE,draftTemplate,DEFAULT_OFFER} from '../lib/lead-engine.ts';
const sample=()=>parseCSV(SAMPLE_CSV);
const lead=(patch={})=>deduplicate([{...sample()[0],...patch}])[0];
test('sample has 10 records, 9 unique leads, 2 ready, 5 held and 2 excluded',()=>{const rows=sample(),leads=deduplicate(rows);assert.equal(rows.length,10);assert.equal(leads.length,9);const states=leads.map(l=>qualify(l,SAMPLE_DATE).state);assert.equal(states.filter(s=>s==='ready').length,2);assert.equal(states.filter(s=>s==='hold').length,5);assert.equal(states.filter(s=>s==='excluded').length,2);});
test('opt-out wins across duplicates; case and spaces normalize',()=>{const rows=sample();rows[6].opted_out='true';const merged=deduplicate(rows)[0];assert.equal(merged.sources.length,2);assert.equal(qualify(merged,SAMPLE_DATE).state,'excluded');});
test('one active-customer flag excludes the entire group',()=>{const rows=sample();rows[6].active_customer='yes';assert.equal(qualify(deduplicate(rows)[0],SAMPLE_DATE).state,'excluded');});
test('same company, different email is not a duplicate',()=>{const r=sample()[0];assert.equal(deduplicate([r,{...r,email:'different@example.com'}]).length,2);});
test('quoted commas, escaped quotes, newlines, BOM and trailing empty cells parse',()=>{const r=parseCSV('\uFEFFname,email,notes,company\r\n"Doe, Jane",jane@example.com,"Said ""hello""\nAsked to reconnect",\r\n')[0];assert.equal(r.name,'Doe, Jane');assert.equal(r.notes,'Said "hello"\nAsked to reconnect');assert.equal(r.company,'');});
test('malformed CSV gives actionable errors',()=>{assert.throws(()=>parseCSV('name,email,notes\na,b'),/Record 2/);assert.throws(()=>parseCSV('name,email,notes\n"a,b,c'),/not closed/);assert.throws(()=>parseCSV('name,email,notes\n"a"x,b,c'),/after a quote/);assert.throws(()=>parseCSV('name,email,email_address,notes\na,b,b,c'),/same field/);});
test('missing flags are unknown and held',()=>assert.equal(qualify(lead({opted_out:''}),SAMPLE_DATE).state,'hold'));
test('future follow-up and recent contact are held',()=>{assert.match(qualify(lead({next_followup:'2026-11-01'}),SAMPLE_DATE).reason,/not due/);assert.match(qualify(lead({last_contact:'2026-09-01'}),SAMPLE_DATE).reason,/30 days/);});
test('invalid calendar dates and future contact are held',()=>{assert.equal(dateValue('2026-02-30'),null);assert.equal(dateValue('09/01/2026'),null);assert.equal(qualify(lead({last_contact:'2026-02-30'}),SAMPLE_DATE).state,'hold');assert.match(qualify(lead({last_contact:'2027-01-01'}),SAMPLE_DATE).reason,/future/);});
test('identity conflicts across matching email are held',()=>{const r=sample()[0];assert.match(qualify(deduplicate([r,{...r,name:'Different Person'}])[0],SAMPLE_DATE).reason,/Conflicting/);});
test('missing follow-up date and stale history are held',()=>{assert.equal(qualify(lead({next_followup:''}),SAMPLE_DATE).state,'hold');assert.match(qualify(lead({last_contact:'2024-02-01'}),SAMPLE_DATE).reason,/year old/);});
test('CSV exports guard spreadsheet formula injection',()=>{const l=lead({name:'=HYPERLINK("bad")',company:' +SUM(1,2)'});const csv=exportCSV([l]);assert.ok(csv.includes('"\'=HYPERLINK'));assert.ok(csv.includes('"\' +SUM'));});
test('template uses declared offer and retains source evidence',()=>{const l=lead();const r=draftTemplate(l,DEFAULT_OFFER);assert.ok(r.draft.includes(DEFAULT_OFFER));assert.ok(r.evidence[0].includes(l.notes));assert.ok(!r.draft.includes('guarantee'));});
test('repeated processing is deterministic',()=>{const one=deduplicate(sample()).map(l=>qualify(l,SAMPLE_DATE));assert.deepEqual(one,deduplicate(sample()).map(l=>qualify(l,SAMPLE_DATE)));});
